using System.Security.Cryptography.X509Certificates;

namespace UpdateWatch2.Server.Certificates;

/// <summary>Result of issuing a new agent client certificate.</summary>
public record IssuedCertificate(byte[] PfxBytes, string ThumbprintSha256, DateTimeOffset IssuedAt, DateTimeOffset ExpiresAt);

/// <summary>
/// Snapshot of the CA's rotation state (updatewatch2-server#6), returned to
/// the admin UI. <see cref="PreviousThumbprint"/> is non-null only in the
/// window between an activation and either the previous root's natural
/// expiry or an admin explicitly retiring it. <see cref="PendingThumbprint"/>
/// is non-null only between a prepare and its matching activate.
/// </summary>
public record CaRotationStatus(
    string CurrentThumbprint, DateTimeOffset CurrentNotAfter,
    string? PreviousThumbprint, DateTimeOffset? PreviousNotAfter,
    string? PendingThumbprint, DateTimeOffset? PendingNotAfter);

/// <summary>
/// UpdateWatch2's internal, self-signed certificate authority — the root of
/// trust for agent-server mutual TLS (see CLAUDE.md "Certificate-based
/// mutual auth is the security backbone"). No external CA/ACME integration;
/// see the class-level doc comment on <see cref="InternalCertificateAuthority"/>
/// for why, and for root rotation (updatewatch2-server#6), the one
/// follow-up issue that deliberately stayed open when this class was first
/// written.
/// </summary>
public interface ICertificateAuthority
{
    /// <summary>
    /// The CURRENT root CA certificate (public + private key, in-memory
    /// only — never sent to a client as-is) — the one used to sign new
    /// agent leaves and the server's own leaf. Its public half is part of
    /// what <c>GET /api/agent/ca-certificate</c>/<c>ca-certificates</c> hand
    /// out, and what both the server's cert-auth middleware and agents pin
    /// as a trust anchor. Changes identity (a different underlying
    /// <see cref="X509Certificate2"/>) the moment <see cref="ActivateRotation"/>
    /// runs — callers must not cache this instance across a rotation.
    /// </summary>
    X509Certificate2 RootCertificate { get; }

    /// <summary>
    /// The root superseded by the most recent <see cref="ActivateRotation"/>
    /// call, if any — still trusted (present in
    /// <see cref="TrustedRootCertificates"/>) so an agent client leaf issued
    /// under it keeps validating until it naturally renews under the new
    /// current root, but no longer used to sign anything new. Null outside
    /// an active rotation's overlap window.
    /// </summary>
    X509Certificate2? PreviousRootCertificate { get; }

    /// <summary>
    /// A root generated by <see cref="PrepareRotation"/> but not yet
    /// promoted to <see cref="RootCertificate"/> by <see cref="ActivateRotation"/>.
    /// Published (alongside <see cref="RootCertificate"/>) via
    /// <c>GET /api/agent/ca-certificates</c> so an already-onboarded agent
    /// can pre-trust it ahead of activation, but deliberately excluded from
    /// <see cref="TrustedRootCertificates"/> — nothing is signed by it yet,
    /// so there is nothing for it to validate.
    /// </summary>
    X509Certificate2? PendingRootCertificate { get; }

    /// <summary>
    /// Every root a client certificate is currently allowed to chain to for
    /// mutual-TLS authentication — <see cref="RootCertificate"/> plus
    /// <see cref="PreviousRootCertificate"/> when present. A single,
    /// long-lived, mutable instance: <c>Program.cs</c> hands this exact
    /// object to <c>CertificateAuthenticationOptions.CustomTrustStore</c>
    /// once at startup, so a later rotation mutating its contents (via
    /// <see cref="ActivateRotation"/>/<see cref="RetirePreviousRoot"/>) takes
    /// effect on already-running request handling immediately — no options
    /// reload, no restart.
    /// </summary>
    X509Certificate2Collection TrustedRootCertificates { get; }

    /// <summary>
    /// Every root this CA currently knows about at all —
    /// <see cref="RootCertificate"/>, <see cref="PreviousRootCertificate"/>,
    /// and <see cref="PendingRootCertificate"/> where each is present. What
    /// <c>GET /api/agent/ca-certificates</c> publishes; broader than
    /// <see cref="TrustedRootCertificates"/> specifically so a pending root
    /// reaches agents before it's actually trusted for anything.
    /// </summary>
    X509Certificate2Collection AllKnownRootCertificates { get; }

    /// <summary>
    /// The server's own current TLS leaf (the one Kestrel presents on the
    /// agent-facing port) — read on every new TLS connection via Kestrel's
    /// <c>ServerCertificateSelector</c> rather than captured once at
    /// startup, specifically so <see cref="ActivateRotation"/> re-issuing it
    /// under the new root takes effect immediately, with no service
    /// restart, the same "no restart required" bar this project already
    /// holds admin-mediated agent certificate re-issuance to
    /// (updatewatch2-server#8).
    /// </summary>
    X509Certificate2 CurrentServerLeaf { get; }

    /// <summary>
    /// Loads the server's own TLS leaf certificate, generating or
    /// regenerating it as needed so its SAN always matches
    /// <paramref name="sanHostname"/> AND it still chains to the CURRENT
    /// root — see <see cref="InternalCertificateAuthority"/>'s remarks on
    /// why a mismatch on either front triggers silent regeneration rather
    /// than requiring a manual step. Must be called once at startup before
    /// <see cref="CurrentServerLeaf"/> is read.
    /// </summary>
    X509Certificate2 EnsureServerLeaf(string sanHostname);

    /// <summary>
    /// Issues a brand-new client certificate for an approved agent, signed by
    /// the CURRENT <see cref="RootCertificate"/>, Subject CN = <paramref name="hostname"/>,
    /// Enhanced Key Usage = Client Authentication only, valid for
    /// <paramref name="validity"/> from issuance (updatewatch2-server#9 —
    /// the caller is responsible for sourcing this, typically from the
    /// live admin-configured <c>CertificateOptions.AgentCertificateValidityDays</c>;
    /// this class deliberately stays unaware of admin settings entirely).
    /// </summary>
    IssuedCertificate IssueAgentLeaf(string hostname, TimeSpan validity);

    /// <summary>A read-only snapshot of the current rotation state, for the admin UI.</summary>
    CaRotationStatus GetRotationStatus();

    /// <summary>
    /// Generates a new root and persists it as "pending" — not yet used to
    /// sign anything, not yet added to <see cref="TrustedRootCertificates"/>,
    /// but published via <c>GET /api/agent/ca-certificates</c> immediately so
    /// already-onboarded agents can start pre-trusting it ahead of an
    /// eventual <see cref="ActivateRotation"/>. Calling this again while a
    /// pending root already exists replaces it with a fresh one (safe: a
    /// pending root that was never activated never signed anything an agent
    /// depends on).
    /// </summary>
    X509Certificate2 PrepareRotation();

    /// <summary>
    /// Promotes the pending root (from <see cref="PrepareRotation"/>) to
    /// current, demotes the current root to previous (discarding any
    /// older previous — only two generations are ever kept at once), and
    /// immediately re-issues the server's own leaf under the new current
    /// root. Throws if no root is pending. An admin should only call this
    /// once enough time has passed on the heartbeat cadence for
    /// already-onboarded agents to have fetched and pre-trusted the pending
    /// root — activating too early can otherwise briefly break an agent
    /// that hasn't picked it up yet, since the server's leaf switches roots
    /// at this exact moment.
    /// </summary>
    void ActivateRotation();

    /// <summary>
    /// Drops the previous root entirely — it stops validating any
    /// still-not-yet-renewed agent client leaf signed under it. An admin
    /// should only call this once satisfied every agent has renewed past
    /// it (or simply once it has naturally expired). Throws if there is no
    /// previous root.
    /// </summary>
    void RetirePreviousRoot();
}
