// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpdateWatch2.Server.Db;

#nullable disable

namespace UpdateWatch2.Server.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904100922_FixLegacyAdSettingsDefaults")]
    partial class FixLegacyAdSettingsDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("UpdateWatch2.Server.Db.Entities.AdminAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminAccounts");
                });

            modelBuilder.Entity("UpdateWatch2.Server.Db.Entities.AdminSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdBaseDn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdBindDn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdBindPassword")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdEncryption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdLoginGroupDn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdUserSearchFilter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BruteForceLockoutMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BruteForceMaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BruteForceWindowMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationAffectedMachinesThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotificationUpdatesPerMachineThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpEncryption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpFromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpFromName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminSettings");
                });

            modelBuilder.Entity("UpdateWatch2.Server.Db.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClientCertificateExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClientCertificateIssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientCertificateThumbprint")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DnsName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAliveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("TEXT");

                    b.Property<int>("PendingUpdateCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RebootRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationTokenHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("UpdateWatch2.Server.Db.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogEntries");
                });

            modelBuilder.Entity("UpdateWatch2.Server.Db.Entities.UpdateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Installed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("UpdateItems");
                });

            modelBuilder.Entity("UpdateWatch2.Server.Db.Entities.UpdateItem", b =>
                {
                    b.HasOne("UpdateWatch2.Server.Db.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });
#pragma warning restore 612, 618
        }
    }
}
